- job:
    name: openstack-chef-repo-rake
    parent: base
    description: Run rake tests with openstack-chef-repo
    required-projects: openstack/openstack-chef-repo
    pre-run: playbooks/pre
    run: playbooks/rake

- job:
    name: openstack-chef-repo-integration
    parent: base
    description: Run integration tests with openstack-chef-repo
    required-projects: openstack/openstack-chef-repo
    pre-run: playbooks/pre
    run: playbooks/integration
    post-run: playbooks/post
    timeout: 3600

- project-template:
    name: openstack-chef-repo-jobs
    check:
      jobs:
        - openstack-chef-repo-rake
        - openstack-chef-repo-integration
    gate:
      jobs:
        - openstack-chef-repo-rake
        - openstack-chef-repo-integration

- project:
    name: openstack/openstack-chef-repo
    templates:
      - openstack-chef-repo-jobs
